spring:
  application:
    endpoints:
      api:
        order_paypal:
          base: http://localhost:7120/api/v1/order-paypal
          find_order_not_excluded: http://localhost:7062/api/v1/order-paypal/find-order-not-excluded
        student:
          base: http://localhost:7110/api/v1/student/
          findAllProfilesByIdentityIds: http://localhost:7110/api/v1/student/findAllProfilesByIdentityId/
        agenda:
          base: http://loc  alhost:7093/api/v1/agenda/
          findAgendasForStudentInDateRange: http://localhost:7093/api/v1/agenda/findAgendasForStudentInDateRange/
        identity:
          base: http://localhost:7083/api/v1/identity/
          findbyidentityids: http://localhost:7083/api/v1/identity/ids/
          findbyuserid: http://localhost:7083/api/v1/identity/findByUserId/
        album:
          base: http://localhost:7052/api/v1/album/
          findAvatar: http://localhost:7052/api/v1/file/find-avatar/
        user:
          base: http://localhost:7032/api/v1/user/
