spring:
  application:
    name: service-user
  profiles:
    active: dev
  data:
    mongodb:
      uri: mongodb+srv://root:abc123mdb@cluster0.ktsakb6.mongodb.net/?retryWrites=true&w=majority
      database: altamiram
server:
  port: 7032

eureka:

  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

